### ISSUE TITLE
Cleaning out nested folders generated by webpack

### ISSUE THREAD

**Issue by phinett** [gpbl/webpack-cleanup-plugin#11]
My webpack outputs into multiple nested folders, but this cleanup plugin empties these nested folders. Appears it only works on the root directory.

**Comment by gpbl** [comment]
Hi @phinett, @aderugin 

could please you provide a .json stats file generated by a webpack creating nested folders? So that I can replicate this issue. The plugin reads the `assets` array in it – you need just to copy/paste its content.

Thanks!

**Comment by gpbl** [comment]
This should have been solved already in [v0.4](https://github.com/gpbl/webpack-cleanup-plugin/blob/master/CHANGELOG.md#v040-2016-09-18).
