### ISSUE TITLE
offset does not account for './' in path

### ISSUE THREAD

**Issue by ghost** [gpbl/webpack-cleanup-plugin#15]
For example, if my outputPath is set to './build', the offset is set to 8, so instead of `./build/bundle.js` I get `./build/ndle.js`

I'd be happy to create a PR for it, but wasn't sure if this was a WONTFIX scenario.

**Comment by gpbl** [comment]
Uhm interesting! Could you post your stats somewhere so we can test this case?

**Comment by gpbl** [comment]
I'm super OK for PRs 👍 i'd like first to set up a testing environment.

**Comment by gpbl** [comment]
I was looking to this issue @a-theriault. You should pass an absolute path (e.g. using `__dirname`), as it is required by webpack, see https://github.com/webpack/docs/wiki/Configuration#outputpath). Or am I missing something?

**Comment by gpbl** [comment]
@a-theriault Maybe this was related to #20 fixed in 0.4.1. Please write back if you have some more info, thanks.
