### ISSUE TITLE
Logging results in invalid json with webpack --json flag

### ISSUE THREAD

**Issue by ghost** [gpbl/webpack-cleanup-plugin#19]
When using webpack cleanup plugin and running `webpack --json`, the resulting output json will have the first line as 'WebpackCleanupPlugin: _X_ file(s) deleted.', which invalidates the json output.

This is problematic for other tools which rely on piping valid json from webpack, such as the webpack-bundle-analyzer tool.

**Comment by gpbl** [comment]
Hi @tayden-hakai, the `quiet` option should work for you:

``` js
new WebpackCleanupPlugin({
  quiet: true,
})
```
