### ISSUE TITLE
Include linter config?

### ISSUE THREAD

**Issue by foxbunny** [gpbl/webpack-cleanup-plugin#30]
@gpbl If you use ESLint on the project, it might be a good idea to include the linter configuration and possibly run the linting along with the tests.

**Comment by gpbl** [comment]
Hi @foxbunny thanks for the suggestion. 

The config is already in [.eslintrc](https://github.com/gpbl/webpack-cleanup-plugin/blob/master/.eslintrc), the linter is running before the tests [on travis](https://github.com/gpbl/webpack-cleanup-plugin/blob/master/.travis.yml).

**Comment by foxbunny** [comment]
Ah, sorry, completely missed it.
