### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by evpozdniakov** [gpbl/webpack-cleanup-plugin#6]
It gives me the following error If I call it without parameters `new WebpackCleanupPlugin()`

```
 var _options$exclude = _this.options.exclude;
                                            ^

TypeError: Cannot read property 'exclude' of undefined
```

**Comment by gpbl** [comment]
It should be fixed now with v0.2.0. Feel free to reopen the issue if it doesn't still work. Thanks for the report.
