### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by okiroth** [gpbl/webpack-cleanup-plugin#9]
I am not able to exclude the .git folder from a test project I'm working on. Maybe I'm missing something or is not implemented?

**Comment by mattseburn** [comment]
+1

**Comment by tysonnero** [comment]
+1

**Comment by xQuotes** [comment]
+1

**Comment by gpbl** [comment]
[This PR](https://github.com/gpbl/webpack-cleanup-plugin/pull/18) would fix it.
I'd like to add first some unit tests before publishing the changes on npm, please have some patience thanks!

**Comment by gpbl** [comment]
Hi people, v0.4.0 introduced better file/folder support for the `exclude` option:

E.g. this should exclude the `.git` folder:

``` js
new WebpackCleanupPlugin({ exclude: ['.git/**/*'] });
```

Please reopen if not working as expected, thanks (there's even a new `preview: true` option to preview the files that would be deleted).

**Comment by okiroth** [comment]
@gpbl Thanks a lot! Honestly, thanks for devoting time to this awesome project.
